max_width = 120
ideal_width = 100
report_todo = "Always"
report_fixme = "Unnumbered"
reorder_imports = true
reorder_imported_names = true
wrap_match_arms = false
match_block_trailing_comma = true
where_trailing_comma = true
